---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGV2b3BzMjAyMA==
  MYSQL_DATABASE: ZGV2b3Bz
  MYSQL_USER: ZWxvbg==
  MYSQL_PASSWORD: bXVzaw==
