---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGV2b3BzaW5wcm9ncmVzczIwMjM=
  MYSQL_DATABASE: ZGV2b3Bz
  MYSQL_USER: ZGV2b3BzdXNlcg==
  MYSQL_PASSWORD: bXlzcWxEZXZvcHNpbnByb2dyZXNzIA==