---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - nodePort: 30306
    port: 3306
    protocol: TCP
    targetPort: 3306
